=== Arnaudkote/labd_lille1/TP1/Exercice4/exercice4.dtd
<!ELEMENT voyage (informations_generale_voyage,
marche,etapes)>

<!ELEMENT informations_generale_voyage 
(ville_depart,ville_arr,date_et_heure,
mode,Preference,vitesse_de_marche,parcours_duree
)>

<!ELEMENT ville_depart 
(nom)>


<!ELEMENT nom  (#PCDATA)>


<!ELEMENT ville_arr
(nom)>

<!ELEMENT date_et_heure (#PCDATA)
>


<!ELEMENT mode   (#PCDATA)
>

<!ELEMENT Preference   (#PCDATA)
>

<!ELEMENT vitesse_de_marche   (#PCDATA)
>

<!ELEMENT parcours_duree   (#PCDATA)
>

<!ELEMENT marche   (depart_marche,arrivee_marche,duree)
>

<!ATTLIST depart_marche   mobilite CDATA #IMPLIED
>

<!ELEMENT depart_marche    (#PCDATA)
>

<!ELEMENT arrivee_marche    (#PCDATA)
>

<!ELEMENT duree    (#PCDATA)
>

<!ELEMENT etapes    (etape1,etape2,etape3,etape4)
>

<!ELEMENT etape1    (heure,bus_numero,descendre,duree)
>

<!ELEMENT heure    (#PCDATA)
>

<!ATTLIST bus_numero   direction CDATA #IMPLIED
>

<!ELEMENT bus_numero    (#PCDATA)
>

<!ELEMENT descendre    (#PCDATA)
>

<!ELEMENT etape2    (numero_ligne)
>

<!ELEMENT numero_ligne    (num,depart,arrivee)
>


<!ATTLIST numero_ligne   mobilite CDATA #IMPLIED
>

<!ELEMENT num    (#PCDATA)
>

<!ELEMENT depart    (heure_dep,arret)
>

<!ELEMENT heure_dep    (#PCDATA)
>

<!ELEMENT arret    (#PCDATA)
>
<!ELEMENT arrivee    (heure_arr,arret)
>

<!ELEMENT heure_arr    (#PCDATA)
>

<!ELEMENT etape3    (numero_ligne)
>


<!ELEMENT etape4    (numero_ligne)
>

=== Arnaudkote/labd_lille1/TP1/Exercice4/exercice4.xml
<?xml version="1.0"?>

<!DOCTYPE exercice4 SYSTEM
"exercice4.dtd"> 

<voyage>

<informations_generale_voyage>

<ville_depart>


<nom>Seclin - Centre hospitalier</nom>


</ville_depart>


<ville_arr>


<nom>Roubaix - Avenue Motte</nom>


</ville_arr>

<date_et_heure>

Mardi 22 janvier à 12h35


</date_et_heure>


<mode>

Métro-Tramway-Bus-Car

</mode>

<Preference>

Arriver le plus rapidement

</Preference>


<vitesse_de_marche>

pied Normale

</vitesse_de_marche>


<parcours_duree>


1h 27 min

</parcours_duree>

</informations_generale_voyage>

<marche>


    <depart_marche   mobilite="pied">
	
	Seclin - Centre hospitalier
	</depart_marche>
	
	<arrivee_marche>
	
	Seclin -Hôtel de Ville
	
	</arrivee_marche>
	
	<duree> 13 min </duree>


</marche>


<etapes>

<etape1>

<heure>14h51</heure>

<bus_numero direction="Lille - Porte des Postes"> 

ligne 52

</bus_numero>

<descendre>

 l’arrêt Lille - CHR B Calmette

</descendre>

<duree>

23 min

</duree>

</etape1>

<etape2>

<numero_ligne  direction="Villeneuve d’Ascq - 4 Cantons Grand Stade">

<num>Métro ligne 1</num>

<depart>

<heure_dep>

15h18
</heure_dep>

<arret>

arrêt Lille - CHR B Calmette

</arret>

</depart>


<arrivee>

<heure_arr>

15h21

</heure_arr>

<arret>

 Lille - Porte des Postes


</arret>

</arrivee>

</numero_ligne>


</etape2>

<etape3>

<numero_ligne direction="Tourcoing - CH Dron">

<num>

Métro ligne 2

</num>

<depart>

<arret>

 Lille - Porte des Postes
 
 </arret>
 
 <heure>
 
 15h27
  </heure>
 

</depart>

<arrivee>

<arret>

 Roubaix - Epeule Montesquieu
 
 </arret>
 
 <heure>
 
 15h52
 
 </heure>
 
  </arrivee>
 

</numero_ligne>


</etape3>

<etape4>

<numero_ligne direction="Roubaix - fraternité">

<num> ligne 25 </num>

<depart>

<arret>

arrêt Roubaix - Epeule Montesquieu

</arret>

<heure>

15h56
</heure>

</depart>

<arrivee>

<arret>

arrêt Roubaix - Avenue Motte

</arret>

<heure>

16h05

</heure>

</arrivee>

</numero_ligne>





</etape4>


</etapes>

</voyage>
